services:
  caddy:
    image: caddy:2.8.4-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      # Mount Caddyfile into the container for caddy to use
      - ./config/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
    networks:
      default:
        # Define aliases so that inside the docker network, these services can
        #   also be reached at the specified addresses.
        # keycloak needs to be reached at keycloak.localhost so that its
        #   certificate will be valid (has the right domain name)
        aliases:
          - caddy.localhost
          - keycloak.localhost
          - whoami.localhost

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.6
    volumes:
      - ./config/keycloak/:/keycloak/:ro
    depends_on:
      - caddy
    environment:
      # Use the inbuilt h2 database for demo purposes
      KC_DB: dev-mem
      # Credentials for demo
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    entrypoint: /keycloak/start.sh

  gatekeeper:
    image: quay.io/gogatekeeper/gatekeeper:2.14.3
    volumes:
      - ./config/gatekeeper/:/gatekeeper/:ro
    entrypoint: /gatekeeper/start.sh
    depends_on:
      - keycloak
    # We run as root in this demo so that root can add caddy's self-signed cert
    #   to the system store
    user: root
    environment:
      # Credentials used to login to keycloak - set above
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password

  whoami:
    image: containous/whoami:latest
    depends_on:
      - gatekeeper
